### PR TITLE
Use the CurrencyPairMetaData to find the price scale

### PR DESCRIPTION
**Pull request by scionaltera**
...instead of the CurrencyMetaData which seems to have the wrong values for what we're doing.

This is intended to fix errors that have started to pop up with Kraken saying that we're using the wrong number of decimal places for several currency pairs.

### CODE REVIEW

**Review by dazito — DISMISSED** [review]

**Comment by scionaltera** [comment]
I split up "price" scale and "volume" scale per @AllirionX 's comments on Discord so we're not confusing the two anymore. I also added the same logic into `exitPosition()` since we're likely to have the same problem with price scale there. Before merging I still want to see it make a successful trade on somebody's machine.

**Review by AllirionX — APPROVED** [review]

**Review by AllirionX — CHANGES_REQUESTED** [review]
I am getting java.lang.NullPointerException: null
 at com.r307.arbitrader.service.TradingService.enterPosition(TradingService.java:172)

**Comment by scionaltera** [comment]
> I am getting java.lang.NullPointerException: null
> at com.r307.arbitrader.service.TradingService.enterPosition(TradingService.java:172)

Yeah, I got that too. I've got a debugger ready to catch it the next time it happens. Not sure how it could be getting a null on that line but I'll figure it out.

**Review by dazito — APPROVED** [review]

**Comment by scionaltera** [comment]
I got a successful entry running this branch, so I think it's ready to go.

**Pull request merged**
